sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t alpine-curl .
  - docker build -t alpine-node-onbuild-test tests/
  - docker run -d --name alpine-node-onbuild-test alpine-node-onbuild-test

script:
  - docker run --link alpine-node-onbuild-test:test -it --rm alpine-curl http://test:3000/ | grep 'Hello World!'
